2025-04-02 02:58:07,324 - __main__ - INFO - Iniciando sistema de monitoramento de personagens
2025-04-02 02:58:08,271 - __main__ - INFO - Requisição para Zahir concluída em 0.95 segundos
2025-04-02 02:58:08,271 - __main__ - INFO - Zahir: Offline. Enviando notificação.
2025-04-02 02:58:12,344 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F80521490>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:58:17,016 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F805212E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:58:22,269 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F805218B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:58:26,321 - __main__ - ERROR - Erro ao enviar notificação para Zahir: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /messagem (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F80521A90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')) após 18.05 segundos
2025-04-02 02:58:26,321 - __main__ - ERROR - Falha ao enviar notificação para Zahir. Tentando novamente no próximo ciclo.
2025-04-02 02:58:27,254 - __main__ - INFO - Requisição para Mancolino concluída em 0.93 segundos
2025-04-02 02:58:27,254 - __main__ - INFO - Mancolino: Offline. Enviando notificação.
2025-04-02 02:58:48,164 - __main__ - INFO - Iniciando sistema de monitoramento de personagens
2025-04-02 02:58:49,191 - __main__ - INFO - Requisição para Zahir concluída em 1.03 segundos
2025-04-02 02:58:49,191 - __main__ - INFO - Zahir: Offline. Enviando notificação.
2025-04-02 02:58:53,265 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD1490>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:58:57,939 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD12E0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:03,217 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD18B0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:07,293 - __main__ - ERROR - Erro ao enviar notificação para Zahir: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /messagem (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD1A90>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')) após 18.10 segundos
2025-04-02 02:59:07,293 - __main__ - ERROR - Falha ao enviar notificação para Zahir. Tentando novamente no próximo ciclo.
2025-04-02 02:59:08,280 - __main__ - INFO - Requisição para Mancolino concluída em 0.99 segundos
2025-04-02 02:59:08,281 - __main__ - INFO - Mancolino: Offline. Enviando notificação.
2025-04-02 02:59:12,349 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD22D0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:17,035 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD2390>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:22,283 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BA4DF8F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:26,330 - __main__ - ERROR - Erro ao enviar notificação para Mancolino: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /messagem (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD08F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')) após 18.05 segundos
2025-04-02 02:59:26,330 - __main__ - ERROR - Falha ao enviar notificação para Mancolino. Tentando novamente no próximo ciclo.
2025-04-02 02:59:27,363 - __main__ - INFO - Requisição para Mais Do Mesmo concluída em 1.03 segundos
2025-04-02 02:59:27,363 - __main__ - INFO - Mais Do Mesmo: Offline. Enviando notificação.
2025-04-02 02:59:31,420 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD2480>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:36,050 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD26F0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:41,316 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=3, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD2870>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /messagem
2025-04-02 02:59:45,378 - __main__ - ERROR - Erro ao enviar notificação para Mais Do Mesmo: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /messagem (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F9BACD2AB0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')) após 18.01 segundos
2025-04-02 02:59:45,379 - __main__ - ERROR - Falha ao enviar notificação para Mais Do Mesmo. Tentando novamente no próximo ciclo.
2025-04-02 02:59:46,403 - __main__ - INFO - Requisição para Cleef concluída em 1.02 segundos
2025-04-02 02:59:46,404 - __main__ - INFO - Cleef: Offline. Enviando notificação.
